"""

 - The goal of this program is to read the file given, in this case "coding_qual_input.txt",
   and return the values that would represent the last number in a pyramid.

   EX:

        1       - 1
       2 3      - 3     -> These are the values that are needed.
      4 5 6     - 6

   After knowing the values, print the answer as one full sentence.

 - This was a problem generated by Gemini 3 Pro, problem attached to README.md

 - This is a program created by Noah Sizemore.

"""



# reads the file "str" and opens it returning a list of every line in the file.
def read_file(file_reading: str) -> list[:]:
    #includes a FileNotFound exception
    try:
        with open(file_reading, "r") as opened_file:
            content = opened_file.readlines()
            return content
    except FileNotFoundError:
        print(f"{file_reading} was not found.")


def pyramid_numbers(max_number):

    needed_numbers = []

    current_number = 1
    step = 2

    # Keep generating until we pass the largest number in your file
    while current_number <= max_number:
        needed_numbers.append(current_number)

        # Calculate the next 'end of row' number
        current_number = current_number + step
        step += 1  # Next time, we add one more (add 3, then 4, etc.)

    return needed_numbers


# main method
def main():
    # input
    input_file = str(input("Please type the file directory: "))
    file = read_file(input_file)

    # declaration of the dictionary used in the program
    cleaned_file = {}

    # appending the items into the dictionary
    for i in range(len(file)):
        temp = list(file[i].split())
        cleaned_file[temp[0]] = temp[1]

    # sorting the dictionary numerically
    sorted_cleaned_file = dict(sorted(cleaned_file.items(), key=lambda item: int(item[0])))


    pyramid  = pyramid_numbers(200)


    # determining the items that should be printed out
    for item in pyramid:
        if sorted_cleaned_file.get(str(item)) is not None:
            print(sorted_cleaned_file.get(str(item)), end=" ")



# run the program
if __name__ == "__main__":
    main()